import { NiveauStock } from 'src/app/controller/entities/inventaire/niveau-stock';
import { Devises } from 'src/app/controller/entities/parametres/devises';
import { Taxe } from 'src/app/controller/entities/parametres/taxe';
import { ProduitNiveauPrix } from 'src/app/controller/entities/produit/produit-niveau-prix';
import { EstimationProduit } from 'src/app/controller/entities/ventes/estimation/estimation-produit';
import { CommandeProduit } from 'src/app/controller/entities/ventes/commande/commande-produit';
import { FactureProduit } from 'src/app/controller/entities/ventes/facture/facture-produit';
import { DevisProduit } from 'src/app/controller/entities/ventes/devis/devis-produit';
import { RetourProduitProduit } from 'src/app/controller/entities/ventes/retourproduit/retour-produit-produit';
import { NoteCreditProduit } from 'src/app/controller/entities/ventes/notecredit/note-credit-produit';
import { RemboursementProduit } from 'src/app/controller/entities/ventes/remboursement/remboursement-produit';
import { BonCommandeProduit } from 'src/app/controller/entities/inventaire/boncommande/bon-commande-produit';
import { LivraisonProduit } from 'src/app/controller/entities/inventaire/livraison/livraison-produit';
import { Fournisseur } from 'src/app/controller/entities/contacts/fournisseur';
import { Entreprise } from 'src/app/controller/entities/parametres/entreprise';
export class Produit {
id!: number;
nom?: string ;
sku?: string ;
barcode?: string ;
coutInitial!: number;
quantiteMinimumCommandeClient!: number;
niveauStockInitial!: number;
emplacementDeBac?: string ;
pointCommande!: number;
prixGros!: number;
prixDetailRecommande!: number;
prixAchat!: number;
niveauStock?: NiveauStock ;
devises?: Devises ;
taxe?: Taxe ;
produitNiveauPrix?: Array<ProduitNiveauPrix> ;
estimationProduit?: Array<EstimationProduit> ;
commandeProduit?: Array<CommandeProduit> ;
factureProduit?: Array<FactureProduit> ;
devisProduit?: Array<DevisProduit> ;
retourProduitProduit?: Array<RetourProduitProduit> ;
noteCreditProduit?: Array<NoteCreditProduit> ;
remboursementProduit?: Array<RemboursementProduit> ;
bonCommandeProduit?: Array<BonCommandeProduit> ;
livraisonProduit?: Array<LivraisonProduit> ;
fournisseur?: Fournisseur ;
entreprise?: Entreprise ;
disponible!: number;
}
