name: Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: sudo docker build -t laila23/angular-app:latest .

      - name: Publish image to Docker Hub
        run: sudo docker push laila23/angular-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull image from Docker Hub
        run: sudo docker pull laila23/angular-app:latest

      - name: Delete old container
        run: sudo docker rm -f angular-app-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 4200:80 --name angular-app-container laila23/angular-app:latest
